import { PrismaClient, PotMaterial } from '../generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { HEALTH_LABELS } from '../src/lib/health'
import 'dotenv/config'

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
})

const prisma = new PrismaClient({
  adapter,
})

const siteIndexMap: Record<string, number> = {
  'Bedroom (Dresser)': 1,
  'Bedroom (Right Window)': 2,
  'Bedroom (Left Window)': 3,
  'Greenhouse (Shelf 1)': 4,
  'Greenhouse (Shelf 2)': 5,
  'Greenhouse (Shelf 3)': 6,
  'Living Room (Left Window)': 7,
  'Living Room (Right Window)': 8,
  'Living Room (Indirect)': 9,
  'Living Room (Shelf 4)': 10,
  'Living Room (Shelf 3)': 11,
  'Living Room (Shelf 2)': 12,
  'Living Room (Shelf 1)': 13,
}

const siteData = [
  { name: 'Bedroom (Dresser)', index: 1 },
  { name: 'Bedroom (Right Window)', index: 2 },
  { name: 'Bedroom (Left Window)', index: 3 },
  { name: 'Greenhouse (Shelf 1)', index: 4 },
  { name: 'Greenhouse (Shelf 2)', index: 5 },
  { name: 'Greenhouse (Shelf 3)', index: 6 },
  { name: 'Living Room (Left Window)', index: 7 },
  { name: 'Living Room (Right Window)', index: 8 },
  { name: 'Living Room (Indirect)', index: 9 },
  { name: 'Living Room (Shelf 4)', index: 10 },
  { name: 'Living Room (Shelf 3)', index: 11 },
  { name: 'Living Room (Shelf 2)', index: 12 },
  { name: 'Living Room (Shelf 1)', index: 13 },
]

const plantData = [
  {
    name: 'Anthurium gracile',
    health: HEALTH_LABELS['Fair'],
    siteId: siteIndexMap['Greenhouse (Shelf 2)'],
    source: 'Natalie John',
  },
  {
    name: 'Anthurium misturatum',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-10-12'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Ecuagenera',
    dateAcquired: new Date('2025-09-20'),
    cost: 35,
  },
  {
    name: 'Anthurium Titanium',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Greenhouse (Shelf 3)'],
    source: 'Ecuagenera',
  },
  {
    name: 'Anthurium warocqueanum esmeraldense',
    health: HEALTH_LABELS['Fair'],
    siteId: siteIndexMap['Greenhouse (Shelf 3)'],
    source: 'Ecuagenera',
  },
  {
    name: 'Begonia maculata',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Alanna',
  },
  {
    name: 'Bird of Paradise',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Copilot',
  },
  {
    name: 'Cebu Blue Pothos',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Bedroom (Right Window)'],
    propagation: false,
    potSize: 5,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Catherine Palileng Sangoco-Zanghi - NYC Plant Exchange',
    cost: 3.13,
  },
  {
    name: 'Chameleon ZZ Plant',
    health: HEALTH_LABELS['Great'],
    updatedAt: new Date('2023-02-18'),
    siteId: siteIndexMap['Bedroom (Right Window)'],
    propagation: false,
    potSize: 6,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Da Hing',
    cost: 45,
  },
  {
    name: 'Epipremnum pinnatum albo',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Bedroom (Right Window)'],
    propagation: false,
    potSize: 5,
    potMaterial: PotMaterial.PLASTIC,
    source: 'NYC Plant Swap',
    cost: 0,
  },
  {
    name: 'Florida Green cutting',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    propagation: true,
    source: 'Plant Corner',
  },
  {
    name: 'Golden pothos',
    health: HEALTH_LABELS['Great'],
    siteId: siteIndexMap['Bedroom (Dresser)'],
    propagation: false,
    potSize: 8,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Home Depot, propagated from Mom',
    cost: 10,
  },
  {
    name: 'Harlequin pothos',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2023-02-13'),
    siteId: siteIndexMap['Bedroom (Left Window)'],
    propagation: false,
    potSize: 4,
    potMaterial: PotMaterial.PLASTIC,
    source: 'NYC Plant Swap',
    cost: 0,
  },
  {
    name: 'Hoya krimson queen',
    health: HEALTH_LABELS['Great'],
    updatedAt: new Date('2022-09-30'),
    siteId: siteIndexMap['Greenhouse (Shelf 1)'],
    potSize: 4,
    potMaterial: PotMaterial.PLASTIC,
    source: 'Da Hing',
    cost: 15,
  },
  {
    name: 'Hoya lacunosa',
    health: HEALTH_LABELS['Great'],
    siteId: siteIndexMap['Greenhouse (Shelf 1)'],
    propagation: false,
    potSize: 2,
    potMaterial: PotMaterial.PLASTIC,
    source: 'LES Plant Swap',
    cost: 0,
  },
  {
    name: 'Jade plant',
    health: HEALTH_LABELS['Great'],
    siteId: siteIndexMap['Living Room (Right Window)'],
    propagation: false,
    potSize: 3.25,
    potMaterial: PotMaterial.TERRACOTTA,
    source: 'Mrs. Berger via Phliip',
    cost: 0,
  },
  {
    name: 'Jade plant 2',
    health: HEALTH_LABELS['Great'],
    siteId: siteIndexMap['Living Room (Right Window)'],
    source: 'Propagation',
  },
  {
    name: 'Lemon lime philodendron',
    health: HEALTH_LABELS['Good'],
    siteId: siteIndexMap['Bedroom (Left Window)'],
    propagation: false,
    potSize: 4,
    potMaterial: PotMaterial.CERAMIC,
    source: 'LES Plant Swap',
    cost: 0,
  },
  {
    name: 'Monstera adansonii',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Living Room (Left Window)'],
  },
  {
    name: 'Monstera Albo',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Greenhouse (Shelf 1)'],
    propagation: false,
    potSize: 6,
    potMaterial: PotMaterial.PLASTIC,
    source: 'Bing Liang',
    cost: 180,
  },
  {
    name: 'Monstera deliciosa',
    health: HEALTH_LABELS['Great'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    propagation: false,
    potSize: 9.5,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Da Hing',
    cost: 50,
  },
  {
    name: 'Monstera peru',
    health: HEALTH_LABELS['Poor'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Shelf 3)'],
    potSize: 6,
    potMaterial: PotMaterial.PLASTIC,
    source: 'Da Hing',
    cost: 35,
  },
  {
    name: 'Monstera Thai Constellation',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2024-04-04'),
    siteId: siteIndexMap['Living Room (Shelf 1)'],
    potSize: 7,
    potMaterial: PotMaterial.PLASTIC,
    source: 'NYC Plant Exchange',
    cost: 200,
  },
  {
    name: 'Myrtillocactus geometrizans Fukurokuryuzinboku',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Left Window)'],
    source: 'Da Hing',
    cost: 35,
  },
  {
    name: 'Nerve Plant',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Alanna',
  },
  {
    name: 'Peperomia obtusifolia',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Alanna',
    cost: 0,
  },
  {
    name: 'Peperomia tetragona',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Alanna',
  },
  {
    name: 'Peperomia tetraphylla "Hope"',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2026-03-28'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Alanna',
  },
  {
    name: 'Peperomia tetraphylla?',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Alanna',
  },
  {
    name: 'Philodendron 69686',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-08-29'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    potSize: 4,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Geometry',
    dateAcquired: new Date('2025-08-29'),
    cost: 19,
  },
  {
    name: 'Philodendron bicolor',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2025-09-28'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Ecuagenera',
    dateAcquired: new Date('2025-09-20'),
    cost: 30,
  },
  {
    name: 'Philodendron billietiae',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2024-04-04'),
    siteId: siteIndexMap['Living Room (Shelf 2)'],
    potSize: 4,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Da Hing',
    dateAcquired: new Date('2024-04-04'),
    cost: 30,
  },
  {
    name: 'Philodendron brasil',
    health: HEALTH_LABELS['Good'],
    siteId: siteIndexMap['Bedroom (Left Window)'],
    propagation: false,
    potSize: 4,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Sal',
    cost: 0,
  },
  {
    name: 'Philodendron camposportoanum cuttings',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    propagation: false,
    potSize: 2,
    potMaterial: PotMaterial.PLASTIC,
    source: 'NYC Plant Swap',
    cost: 0,
  },
  {
    name: 'Philodendron esmeraldense',
    health: HEALTH_LABELS['Fair'],
    siteId: siteIndexMap['Living Room (Shelf 2)'],
    source: 'Ecuagenera',
  },
  {
    name: 'Philodendron Florida Green',
    health: HEALTH_LABELS['Good'],
    siteId: siteIndexMap['Living Room (Shelf 3)'],
    source: 'Plant Corner',
  },
  {
    name: 'Philodendron gloriosum zebra',
    health: HEALTH_LABELS['Poor'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Greenhouse (Shelf 3)'],
    potSize: 6,
    potMaterial: PotMaterial.PLASTIC,
    source: 'Ecuagenera',
    cost: 70,
  },
  {
    name: "Philodendron Mccolley's Finale",
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    potSize: 6,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Da Hing',
    cost: 20,
  },
  {
    name: 'Philodendron Pink Glory',
    health: HEALTH_LABELS['Good'],
    siteId: siteIndexMap['Living Room (Indirect)'],
    source: 'Ecuagenera',
  },
  {
    name: 'Philodendron pink princess',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Shelf 3)'],
    propagation: false,
    potSize: 6,
    potMaterial: PotMaterial.PLASTIC,
    source: 'PetAl',
    cost: 50,
  },
  {
    name: 'Philodendron rojo congo',
    health: HEALTH_LABELS['Good'],
    siteId: siteIndexMap['Living Room (Shelf 1)'],
    propagation: false,
    potSize: 6,
    potMaterial: PotMaterial.CERAMIC,
    source: 'The Old Yew Popup',
    cost: 0,
  },
  {
    name: 'Philodendron silver sword',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2023-08-07'),
    siteId: siteIndexMap['Bedroom (Left Window)'],
    propagation: false,
    potSize: 4,
    potMaterial: PotMaterial.PLASTIC,
    source: 'Robin at LES Plant Swap',
    cost: 0,
  },
  {
    name: 'Philodendron squamicaule pink',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2025-09-28'),
    siteId: siteIndexMap['Greenhouse (Shelf 2)'],
    source: 'Ecuagenera',
    dateAcquired: new Date('2025-09-20'),
    cost: 40,
  },
  {
    name: 'Philodendron white knight',
    health: HEALTH_LABELS['Good'],
    siteId: siteIndexMap['Greenhouse (Shelf 2)'],
    source: 'Da Hing',
  },
  {
    name: "Pothos N'joy",
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2023-08-07'),
    siteId: siteIndexMap['Bedroom (Left Window)'],
    propagation: false,
    potSize: 4,
    potMaterial: PotMaterial.PLASTIC,
    source: 'Catherine P',
    cost: 3.13,
  },
  {
    name: 'Raven ZZ',
    health: HEALTH_LABELS['Great'],
    updatedAt: new Date('2023-01-04'),
    siteId: siteIndexMap['Bedroom (Right Window)'],
    propagation: false,
    potSize: 6,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Da Hing',
    cost: 35,
  },
  {
    name: 'Rubber Plant',
    health: HEALTH_LABELS['Fair'],
    siteId: siteIndexMap['Bedroom (Dresser)'],
    propagation: false,
    potSize: 6,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Mom',
    cost: 0,
  },
  {
    name: 'Rubber Plant 2',
    health: HEALTH_LABELS['Fair'],
    updatedAt: new Date('2026-02-16'),
    siteId: siteIndexMap['Bedroom (Dresser)'],
  },
  {
    name: 'Staghorn fern',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Left Window)'],
    source: 'Plant Corner',
  },
  {
    name: 'Syngonium albo',
    health: HEALTH_LABELS['Good'],
    siteId: siteIndexMap['Living Room (Shelf 4)'],
    propagation: false,
    potSize: 4,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Da Hing',
    cost: 45,
  },
  {
    name: 'ZZ Plant',
    health: HEALTH_LABELS['Good'],
    updatedAt: new Date('2025-09-15'),
    siteId: siteIndexMap['Living Room (Indirect)'],
    propagation: false,
    potSize: 7.5,
    potMaterial: PotMaterial.CERAMIC,
    source: 'Mom',
    cost: 0,
  },
]

export async function main() {
  for (const s of siteData) {
    await prisma.site.upsert({
      where: { name: s.name },
      update: { index: s.index },
      create: s,
    })
  }

  for (const p of plantData) {
    const { siteId, ...plantFields } = p
    await prisma.plant.upsert({
      where: { name: p.name },
      update: {
        ...plantFields,
        ...(siteId !== undefined ? { site: { connect: { id: siteId } } } : {}),
      },
      create: {
        ...plantFields,
        ...(siteId !== undefined ? { site: { connect: { id: siteId } } } : {}),
      },
    })
  }
}

main()
